name: Tests
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23
      - name: GoReportCard
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl --fail --request POST "https://goreportcard.com/checks" --data "repo=github.com/erfandiakoo/pishgamrayan-go"